### ISSUE TITLE
Atom-editor: is python patch still required?

### ISSUE THREAD

**Issue by andya9** [jreese/arch#5]
Hi, I’m the new maintainer of https://aur4.archlinux.org/packages/atom-editor-git

Is the python patch still required, if we export path during build? 
The official [build instructions] (https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md) don’t mention it. I tried building without, and it (seems to) work just fine.

**Comment by jreese** [comment]
I'm not sure.  The patch was required because Atom wasn't compatible with python 3, but Atom expected the default Python version to be 2.x.  If that changed, then the patch may not be necessary anymore.

**Comment by andya9** [comment]
Thank’you for answering; I tried compiling without the patch, just exporting PYTHON=/usr/bin/python2 before building, and it worked fine; I was wondering: the patch affects only building, or will be used after installation too? (if you already know) 
If it doesn’t, I think we can get rid of it

**Comment by jreese** [comment]
I'm not that sure anymore.  If you can install the new package on a clean machine without needing to export PYTHON=/usr/bin/python2, then I think it would be safe to drop the patch.

**Comment by andya9** [comment]
Thank’you @jreese ! I’ll test a bit more on my machine, and then decide what to do
